apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-data-pv
  namespace: core
spec:
  storageClassName: longhorn
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
  claimRef:
    namespace: core
    name: spark-data-pvc
---