apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: core
  labels:
    strimzi.io/cluster: polyvaria-cluster
spec:
  replicas: 3
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 3Gi
        deleteClaim: true
        kraftMetadata: shared
---

apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: polyvaria-cluster
  namespace: core
  annotations:
    strimzi.io/node-pools: enabled
    strimzi.io/kraft: enabled
spec:
  kafka:
    version: 3.7.1
    metadataVersion: 3.7-IV4
    listeners:
      - name: external
        port: 9094
        type: cluster-ip
        tls: true
        configuration:
          bootstrap:
            annotations:
              advertisedHost: broker-bootstrap.polyvaria.com
              advertisedPort: '443'
          brokers:
            - broker: 0
              advertisedHost: broker-0.polyvaria.com
              advertisedPort: 443
          brokerCertChainAndKey:
            secretName: polyvaria-wildcard-tls
            certificate: tls.crt
            key: tls.key
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}