apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default-pool
  namespace: core
spec:
  addresses:
  - 192.168.50.240-192.168.50.254
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: default
  namespace: core
spec:
  ipAddressPools:
  - default-pool